// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using b4s.CommunicationOngoing.Data;

#nullable disable

namespace b4s.CommunicationOngoing.Migrations
{
    [DbContext(typeof(B4sDbContext))]
    [Migration("20230118204025_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("b4s.CommunicationOngoing.Models.CommunicationOngoing", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BINARY(16)");

                    b.Property<int?>("CareTeamId")
                        .HasColumnType("INT");

                    b.Property<short>("Chanel")
                        .HasColumnType("SMALLINT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("DATETIME");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("CommunicationOngoings");
                });
#pragma warning restore 612, 618
        }
    }
}
